MAPPING = {
    'applying_for': ['Applying for'],
    'purpose': ['Purpose'],
    'residence_period': ['Residence Period'],
    'title': ['Title', 'Prefix'],
    'name': ['Name of the applicant', 'Applicant Name', 'Name'],
    'place_of_birth': ['Place of Birth'],
    'dob': ['Date of birth', 'DOB', 'Date of Birth'],
    'gender': ['Gender'],
    'marital_status': ['Marital Status'],
    'guardian_relation': ["Father's/Husband's/Guardian's Name", "Father/Husband/Wife/Guardian"],
    'father_name': ["Father's/Husband's", "Father Name", "Father's Name", "Father's/Husband's/Guardian's Name"],
    'mobile': ['Mobile'],
    'email': ['Email'],
    'occupation': ['Occupational Status', 'Occupation'],
    'caste_category': ['Caste category', 'Caste/Category', 'Category'],
    'address': ['House/Flat No.', 'House/Flat No', 'House/Bldg./Apt. No. & Name', 'Address'],
    'locality': ['Locality/Area/Ward', 'Street/Locality/Ward', 'Locality'],
    'district': ['District'],
    'taluka': ['Taluka'],
    'village': ['Village/City', 'Village/Town', 'Village', 'Town'],
    'pincode': ['Pincode'],
    'family_size': ['Total Family Members', 'Total family size', 'family size'],
    'earning_members': ['Total earning members in family', 'Total earning members', 'earning members'],
    'children_count': ['Total No. of Children in family', 'Total No. of Children', 'children'],
    'previous_certificate': ['Any Income certificate was issued to you recently', 'Any Income certificate was issued', 'previous Certificate'],
    'immovable_property': ['Any immovable property'], 
    'property_value': ['Property Value', 'Value of Property'],
    'other_income': ['Any income from other sources', 'Income from other source'],
    'part_no': ['Part No.', 'Part No'],
    'serial_no': ['Serial No.', 'Serial No'],
    'electoral_year': ['Electoral Roll Year'],
    'constituency': ['Constituency'],
    'ration_card': ['Ration Card No.'],
    'property_details': ['Property Details'],
    'id_proof_type': ['ID Proof'], 
    'id_proof_no': ['ID Proof No.', 'ID Proof No'],
    'certify': ['I hereby certify that'] 
}
