MAPPING = {
    'self': ['Self'],
    'relative_or_others': ['Relative\nor others', 'Relative'],
    'purpose': ['Purpose'],
    'where_to_submit': ['Where do you intend to submit the certificate?'],
    'residence_certificate_period': ['Residence Certificate Period'],
    'years': ['Years'],
    'months': ['Months'],
    'title': ['Title', 'Prefix'],
    'name': ['Name of the applicant', 'Name'],
    'dob': ['Date of birth', 'DOB'],
    'place_of_birth': ['Place of birth'],
    'gender': ['Gender'],
    'marital_status': ['Marital Status'],
    'guardian_relation': ['Father/Husband/Guardian/Mother'],
    'father_name': ["Father's/Husband's/Guardian's/Mother's Name"],
    'mobile': ['Mobile No'],
    'email': ['Email ID'],
    'occupation': ['Occupational Status'],
    'previous_certificate': ['Any Residence Certificate was issued earlier?'],
    'voter_id_no': ['Voter ID No'],
    'constituency': ['Constituency'],
    'ration_card_no': ['Ration Card No'],
    'immovable_properties': ['Immovable properties owned by the applicant'],
    'id_proof_type': ['ID Proof'],
    'id_proof_no': ['ID Proof No'],
    'certify': ['I hereby certify that, the above'],
    
    # --- Modal Fields ---
    'house_no': ['Enter House/Flat No.', 'House/Flat No.'],
    'rented_owned': ['drpPremisesType_', 'Rented/Owned'],
    'currently_staying': ['drpCurrentStay_', 'Are you currently staying at below address?'],
    'locality': ['Locality/Area/Ward'],
    'district': ['District'],
    'taluka': ['Taluka'],
    'village': ['Village'],
    'pincode': ['Pincode'],
    'period_of_stay': ['Period of Stay'],
    'from_date': ['From Date'],
    'to_date': ['To Date'],
    'apply_to_concerned_office': ['drpApplyTo_', 'Do you want to apply for the Certificate to the concerned office'],
}
